###eureka server 服务端口号
###服务端口号
server:
#  8100应用
  port: 8100
#  9100应用
#  port: 9100
###eureka 基本信息配置
###服务名称(服务注册到eureka名称)

  # 测试时关闭自我保护机制，保证不可用服务及时踢出
  enable-self-preservation: false
  ##剔除失效服务间隔
  eviction-interval-timer-in-ms: 2000

spring:
  application:
    name: wh-learn-eureka-server
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
#     单server的配置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      集群的时候,相互注册 注册到9100应用
#      defaultZone: http://${eureka.instance.hostname}:9100/eureka/
#      集群的时候相互注册 注册到8100应用
#      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
    ###因为自己是为注册中心，不需要自己注册自己,但是集群时需要注册
    register-with-eureka: false
#    集群时候设置为true
#    register-with-eureka: true
    ###因为自己是为注册中心，不需要检索服务
    fetch-registry: false
#    集群时候设置为true
#    fetch-registry: true




